dist: trusty
os: linux
language: java
jdk: oraclejdk8
services:
  - docker

stages:
  - name: build
  - name: docker-build-push
    if: branch IN (dev, master)

jobs:
  include:
    - stage: build
      script: mvn test
    - stage: docker-build-push
      if: branch = dev
      script: docker build -t petil.azurecr.io/petclinic:dev .; docker push petil.azurecr.io/petclinic:dev;
    - stage: docker-build-push
      if: branch = master
      script: docker build -t lpulles/petclinic:master .; docker push lpulles/petclinic:master;

script: echo "Running Build!"

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

