dist: trusty
os: linux
language: java
jdk: oraclejdk8
services:
  - docker

stages:
  - name: build
  - name: docker-build
    if: branch IN (dev, master)
  - name: docker-push
    if: branch IN (dev, master)

jobs:
  include:
    - stage: build
      script: mvn install
    - stage: docker-build
      if: branch = dev
      script: docker build -t lpulles/petclinic:dev .
    - stage: docker-build
      if: branch = master
      script: docker build -t lpulles/petclinic:master .
    - stage: docker-push
      if: branch = dev
      script: docker push lpulles/petclinic:dev
    - stage: docker-push
      if: branch = master
      script: docker push lpulles/petclinic:master

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

